# rpi5os (see yocto/meta-rpi5os/recipes-core/rpi5os-scripts)
PermitRootLogin no
# For the first login only; sudo ssh-keys-only switches it to "no".
PasswordAuthentication yes
KbdInteractiveAuthentication no
PubkeyAuthentication yes
